# fly.toml app configuration file generated for sehat-api on 2026-06-03T17:29:15+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sehat-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
