"""add_triage_fields_to_patient

Revision ID: 6d747ae8d9b9
Revises: 0005_appointments
Create Date: 2026-06-04 23:09:28.442578

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = '6d747ae8d9b9'
down_revision = '0005_appointments'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('priority', sa.String(length=16), nullable=True))
    op.add_column('patients', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('patients', sa.Column('reasoning', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'reasoning')
    op.drop_column('patients', 'confidence')
    op.drop_column('patients', 'priority')
    # ### end Alembic commands ###
